### ISSUE TITLE
Docker container on Docker hub

### ISSUE THREAD

**Issue by alexanderadam** [graulund/tweetnest#90]
it would be nice to have a container with an optimal installation that could simply be fetched.

And thank you for your work 👍

**Comment by mannion007** [comment]
I'll pick this up

**Comment by simonszu** [comment]
Today i discovered that there are no images on docker hub. I'll look into this myself.

**Comment by simonszu** [comment]
I have made a thing. Check this out: https://hub.docker.com/r/simonszu/tweetnest/

**Comment by alexanderadam** [comment]
@simonszu awesome, thank you!

PS: The repo link on Docker hub is still wrong at the moment. Currently it's `https://github.com/simonszu/dockerfiles` instead `https://github.com/simonszu/tweetnest-docker`.

**Comment by simonszu** [comment]
Yes, it is. I am fairly new to docker, and i was hoping in organizing all my dockerfiles in a single repository. Turns out this wasn't the best idea, since one commit to this repo caused Docker hub to rebuild all the images. I have just re-organized this. 

Please bear with me if there are still some issues, i am currently in the process of migrating my tweetnest instance to this docker image as well, i am quite sure that i will detect the issues for myself. If not, drop me a note. ;)
